### ISSUE TITLE
macOS 10.13: use of undeclared identifier 'InvalidContext' in qtbase

### ISSUE THREAD

**Issue by Dargun** [hunter-packages/Qt#12]
painting/qcoregraphics.mm:81:39: error: use of undeclared identifier 'InvalidContext'
require_action(inContext != NULL, InvalidContext, err = paramErr);
^
painting/qcoregraphics.mm:82:38: error: use of undeclared identifier 'InvalidBounds'
require_action(inBounds != NULL, InvalidBounds, err = paramErr);
^
painting/qcoregraphics.mm:83:37: error: use of undeclared identifier 'InvalidImage'
require_action(inImage != NULL, InvalidImage, err = paramErr);

**Comment by ruslo** [comment]
> should be fixed in qt5.9.2

Meaning we need to update Qt from 5.9.1 to 5.9.2? Not sure why you've added error message and links to bugtracker.

**Comment by Dargun** [comment]
officialy is fixed in qt5.9.2, but i had no time to prove it and i wanted to give some details for someone else to save time.

**Comment by Dargun** [comment]
is there a plan to update in the next time to 5.9.2?

**Comment by ruslo** [comment]
> officialy is fixed in qt5.9.2, but i had no time to prove it

> is there a plan to update in the next time to 5.9.2?

Does the update to 5.9.2 fix the problems for you? Unfortunately Qt update require a lot of stuff done manually, I can do it but for reason :)

**Comment by Dargun** [comment]
okay understand, i'am new here and i try to step in deeper in the stuff to learn how it works to maybe support if i can. I like the idea of hunter ;)
theoretically only the download url of qt sdk needs to be changed or?

**Comment by ruslo** [comment]
> theoretically only the download url of qt sdk needs to be changed or?

Yes, add version to Hunter, create Hunter archive with it and use in your build.

Similar to:
* https://docs.hunter.sh/en/latest/creating-new/update.html

Without submitting new version back to GitHub. Just create local Hunter archive, test it and make sure it fix your problems.

> i'am new here

I really recommend you to start with some tiny project like GTest for experimenting. Make sure you got all the peculiarities before you move to huge and slow building Qt.

**Comment by eraxillan** [comment]
@ruslo Hi, i've stuck with this issue too.
No plans to update Qt at least to 5.9.2?
Thanks

**Comment by ruslo** [comment]
> No plans to update Qt at least to 5.9.2?

@eraxillan In the middle of the March.

For now you can add upstream version of Qt to your own Hunter fork and use this temporary release. `hunter-packages` Qt fork holds only two tiny patches, one for Linux (fix static build of some component) and one for iOS (extend basic functionality). So upstream version should work as-is on OSX without any patches.

**Comment by eraxillan** [comment]
Well, this is pretty soon.
I'm very glad to hear this. And other Qt users (legion of them) too :)

However, are there any other workarounds except of forking Hunter? e.g. rollback Xcode version

**Comment by ruslo** [comment]
> However, are there any other workarounds except of forking Hunter? e.g. rollback Xcode version

I haven't experienced this problem myself so can't give you any advice, sorry.

**Comment by eraxillan** [comment]
@ruslo I've checked my assumption - rollback to Xcode 8.2.1 solves the Qt compilation problem.
Hunter `qt-widgets` example was build successfully.

**Comment by ruslo** [comment]
Qt 5.10.1 added to Hunter: https://github.com/ruslo/hunter/releases/tag/v0.20.23

Note that it's not set as a default to all platforms because of the build issue I've experienced:
* https://github.com/ruslo/hunter/blob/v0.20.23/cmake/configs/default.cmake#L114-L123

Works fine for me only on Windows and OSX.
