### ISSUE TITLE
Add -mp flag to configure step when compiling with "Visual Studio" generator

### ISSUE THREAD

**Issue by Knitschi** [hunter-packages/Qt#13]
This is a feature request. 
When using the package on Windows with Visual Studio it does currently not use multiple cores during the compilation. As this is a package that takes quite long to build, it would be helpful to enable a parallel build by adding the `-mp` option to the `configure` call.

**Comment by ruslo** [comment]
> it would be helpful to enable a parallel build by adding the -mp option to the configure call

So it's about adding `-mp` here:
* https://github.com/ruslo/hunter/blob/3b477ebe7f0c3a72b710a7011076f029a5d0e6f8/cmake/projects/Qt/ep-stages/qt-configure.cmake.in#L87

?

**Comment by Knitschi** [comment]
Yes, there or in the code that uses the template. It is an option to Qt's `configure` tool. It is likely that the option will create an error when it is used when compiling with a non MSVC compiler however. I haven't tryed it though.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
