### ISSUE TITLE
Qt build fail on windows (mingw)

### ISSUE THREAD

**Issue by slollo** [hunter-packages/Qt#15]
Steps to reproduce:
```
git clone https://github.com/ruslo/hunter.git
cd hunter\examples\qt-core
mkdir build 
cd build
cmake -GNinja -DHUNTER_STATUS_DEBUG=ON ..
```
[mingw_hunter_qt.log](https://github.com/hunter-packages/Qt/files/1776606/mingw_hunter_qt.log)

**Comment by ruslo** [comment]
@slollo Do you need any advice in fixing this?

**Comment by slollo** [comment]
Yes, I need help. How to add _WIN32_WINNT definition to build Qt?

I tried to use polly/mingw-c11.cmake and "make" instead of "ninja", but the result is the same.

**Comment by ruslo** [comment]
> How to add _WIN32_WINNT definition to build Qt?

Do you know how to do it by adding flag to `./configure` command? If you can do it there then you can add CMake option with default value to control it from Hunter. Meaning update of Qt build scheme.

> I tried to use polly/mingw-c11.cmake and "make" instead of "ninja", but the result is the same.

Configuration that works (latest CI tests for Qt):
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3164

```
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/Qt/Tools/mingw492_32/bin/gcc.exe
```

Note: we use `gcc.exe` from Qt tools installed from system to build Qt from Hunter, just a coincidence.

`qt-core` removed from CI testing for `mingw` by the way. Have you tried to build `qt-widgets`?

**Comment by slollo** [comment]
qt-widgets example builds with same error.

If I use [mingw](http://www.mingw.org/), then I get the error. But the build is successful with [mingw-w64](https://mingw-w64.org/).

I think the issue should be closed. The problem not in Hunter.
