### ISSUE TITLE
Qt 5.10 does not build on macOS 10.13

### ISSUE THREAD

**Issue by rsnitsch** [hunter-packages/Qt#17]
I'm affected by a build problem that has been fixed in Qt 5.11.

Official bug tracker entry: https://bugreports.qt.io/browse/QTBUG-67545

I tried to add Qt 5.11 to hunter myself by simply copy-pasting the 5.10 CMake files, but I failed. In order for it to work I would have had to add a new CMake file for 5.11 to https://github.com/hunter-packages/QtCMakeExtra/tree/master/cmake, and I do not know how to tell hunter to use a local Git-clone version of hunter-packages/QtCMakeExtra...

**Can you please add the latest Qt 5.11?** I'ld do it myself, but I lack the detailed knowledge of hunter to do so...

**Comment by ruslo** [comment]
> In order for it to work I would have had to add a new CMake file for 5.11 to https://github.com/hunter-packages/QtCMakeExtra/tree/master/cmake, and I do not know how to tell hunter to use a local Git-clone version of hunter-packages/QtCMakeExtra...

Take a look here:
* https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html

> Can you please add the latest Qt 5.11?

For the reference on macOS upstream version of Qt used:
* https://github.com/ruslo/hunter/blob/7c804a9241fbb31a3450caa0fecd1f68c18be3c4/cmake/configs/default.cmake#L115
* https://github.com/ruslo/hunter/blob/7c804a9241fbb31a3450caa0fecd1f68c18be3c4/cmake/projects/Qt/hunter.cmake#L230-L239

I.e. modification of this fork is not required.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
