### ISSUE TITLE
The package does not provide the libGLESv2.dll anymore.

### ISSUE THREAD

**Issue by Knitschi** [hunter-packages/Qt#7]
The package used to create the libGLESv2.dll when compiled with CMAKE_ARGS BUILD_SHARED_LIBS=ON.

On my Windows 10 machine I can now no longer run my executables, because this .dll is missing.

**Comment by ruslo** [comment]
> because this .dll is missing

Can you find this library in `${HUNTER_ROOT}`?

**Comment by Knitschi** [comment]
No its missing in the install/bin folder. I am currently using hunter v0.14.21, and I think it was still there when I used v0.14.12.

**Comment by Knitschi** [comment]
I deleted the qt package and regenerated it and now the dll is there. Maybe the problem was caused by shutting the machine down while hunter was still compiling.

**Comment by ruslo** [comment]
> Maybe the problem was caused by shutting the machine down while hunter was still compiling

No, Hunter designed so in such cases build will trigger again and package installed correctly. Are you sure that changing the version of Hunter archive is not the reason? Note that if you're using cloned version of Hunter you have to do updates manually, see [this note](https://github.com/hunter-packages/gate#notes).

**Comment by Knitschi** [comment]
No in this case I am not using the cloned version. Sorry, at this point I can not tell what went wrong. I will post here, should I encounter the problem again.

**Comment by ruslo** [comment]
Closing inactive discussion.
